### PR TITLE
ar: set runtime linked library search path

### LINKED ISSUE #49: Impossible to install - Error: While trying to apply extra data: apply_extra script failed, exit status 512
I tried to update to the last version and I have a problem.
I removed the flatpak and tried to reinstall and I got the same error.

Any idea ?

Here is the log of a verbose install :

Installing…                                                                                         F: flatpak_dir_pull: Using commit 50d50c1a26163a110abf8dd0539b9f8e6642db09b0bc8abb25e8e221ab6d2571 for pull of ref app/com.microsoft.Teams/x86_64/stable from remote flathub

Installing…                        0%  0 bytes/s
Installing… █                      5%F: Loading https://packages.microsoft.com/repos/ms-teams/pool/main/t/teams/teams_1.3.00.30857_amd64.deb using libsoup

Installing… ██▏                   11%  3,2 MB/s
Installing… ███▍                  17%  4,1 MB/s
Installing… ████▌                 23%  4,3 MB/s
Installing… █████▊                29%  4,4 MB/s  00:09
Installing… ██████▊               34%  4,4 MB/s  00:09
Installing… ████████              40%  4,5 MB/s  00:09
Installing… █████████▏            46%  4,5 MB/s  00:08
Installing… ██████████▏           51%  4,5 MB/s  00:07
Installing… ███████████▍          57%  4,6 MB/s  00:06
Installing… ████████████▌         63%  4,6 MB/s  00:05
Installing… █████████████▊        69%  4,7 MB/s  00:04
Installing… ███████████████       75%  4,7 MB/s  00:04
Installing… ████████████████▏     81%  4,7 MB/s  00:03
Installing… █████████████████▍    87%  4,7 MB/s  00:02
Installing… ██████████████████▌   93%  4,7 MB/s  00:01
Installing… ███████████████████▊  99%  4,7 MB/s  00:00
Installing… ████████████████████ 100%  4,8 MB/s  00:00F: Received 76334658 bytes
F: No checksum specified, getting tip of app/com.microsoft.Teams/x86_64/stable from origin flathub
F: tip resolved to: 50d50c1a26163a110abf8dd0539b9f8e6642db09b0bc8abb25e8e221ab6d2571
F: extracting extra data to /home/calisdecris/.local/share/flatpak/app/com.microsoft.Teams/x86_64/stable/.50d50c1a26163a110abf8dd0539b9f8e6642db09b0bc8abb25e8e221ab6d2571-JOUCX0/files/extra
F: Opening user flatpak installation at path /home/calisdecris/.local/share/flatpak
F: Disallowing ipc access
F: Disallowing network access
F: Running /app/bin/apply_extra 
ar: error while loading shared libraries: libbfd-2.35.1.so: cannot open shared object file: No such file or directory
xz: (stdin): File format not recognized
tar: Child returned status 1
tar: Error is not recoverable: exiting now
Error: While trying to apply extra data: apply_extra script failed, exit status 512                   
error: Failed to install com.microsoft.Teams: While trying to apply extra data: apply_extra script failed, exit status 512

### PR DESCRIPTION
**Pull request by Lctrs**
Closes #49

### CODE REVIEW

**Comment by pspiagicw** [comment]
It shows Error 404 , flatpakref not found.
Can someone give a working method to install the above buid.

**Comment by Lctrs** [comment]
Test builds are cleaned up after a short period of time. I'll retrigger one for you.

bot, build

**Comment by pspiagicw** [comment]
thanks!

**Comment by Lctrs** [comment]
So... did it fixed the issue ?

**Comment by pspiagicw** [comment]
No it didnt.

**Comment by Lctrs** [comment]
@pspiagicw Could you test #59 please ?

**Comment by pspiagicw** [comment]
I sucessfully installed it!,and it works.

**Comment by Lctrs** [comment]
Thanks for your feedback.

**Pull request closed without merging**
