### PR TITLE
Update to 21.08

### PR DESCRIPTION
**Pull request by jwillikers**
Update to the 21.08 runtime.

### CODE REVIEW

**Comment by Lctrs** [comment]
Have you tested it ?

**Comment by jwillikers** [comment]
Only just now, but it seems to be working alright.

**Comment by jwillikers** [comment]
I think a recent update in Fedora Silverblue 34 broke something with the audio so that Teams won't output through my headset. This happens with current version, so that's not a result of the update. Everything seems to work fine running this updated version of the Flatpak in an elementaryOS 6 VM under X11. Video calls are working fine. Besides the issues I mentioned with Fedora Silverblue 34 audio, the updated version is working there under Wayland as expected.

**Comment by Lctrs** [comment]
Thank you @jwillikers

**Pull request merged**
